[package]
name = "grpc-client"
description = "grpc-client."
version = "0.0.0"
authors = ["Andrew Hickman <andrew.hickman1@sky.com>"]
repository = "https://github.com/andrewhickman/grpc-client"
documentation = "https://docs.rs/grpc-client"
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2018"
build = "build.rs"

[profile.release]
lto = true

[dependencies]
anyhow = "1.0.43"
futures = "0.3.16"
serde_json = "1.0.66"
bytes = "1.0.1"
http = "0.2.4"
fs-err = "2.6.0"
once_cell = "1.8.0"
memchr = "2.4.1"
serde-transcode = "1.1.1"
iter-set = "2.0.1"
dirs-next = "2.0.0"
tokio-stream = "0.1.7"
open = "2.0.1"
tracing-subscriber = "0.2.20"
tracing = "0.1.26"
dashmap = "4.0.2"
crossbeam-queue = "0.3.2"

[dependencies.druid]
git = "https://github.com/linebender/druid.git"
branch = "master"
features = ["im", "svg", "serde"]

[dependencies.protobuf]
git = "https://github.com/andrewhickman/rust-protobuf.git"
branch = "master"
features = ["with-serde"]

[dependencies.tonic]
version = "0.5.2"
default-features = false
features = ["transport", "tls", "tls-roots"]

[dependencies.tokio]
version = "1.10.0"
features = ["rt-multi-thread", "sync", "fs"]

[dependencies.syntect]
version = "4.6.0"
default-features = false
features = ["parsing", "regex-onig", "assets", "dump-load"]

[dependencies.serde]
version = "1.0.128"
features = ["derive", "rc"]

[dependencies.kurbo]
version = "0.8.1"
features = ["serde"]

[dependencies.im]
version = "15.0.0"
features = ["serde"]

[build-dependencies]
anyhow = "1.0.43"

[build-dependencies.vergen]
version = "5.1.15"
default-features = false
features = ["git"]
