[package]
name = "grpc-client"
description = "grpc-client."
version = "0.0.0"
authors = ["Andrew Hickman <andrew.hickman1@sky.com>"]
repository = "https://github.com/andrewhickman/grpc-client"
documentation = "https://docs.rs/grpc-client"
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2021"
build = "build.rs"

[profile.release]
lto = true

[dependencies]
anyhow = "1.0.56"
base64 = "0.13.0"
bytes = "1.1.0"
crossbeam-queue = "0.3.4"
dashmap = "5.1.0"
dirs-next = "2.0.0"
fs-err = "2.7.0"
futures = "0.3.21"
http = "0.2.6"
iter-set = "2.0.2"
once_cell = "1.10.0"
open = "2.1.1"
prost = "0.9.0"
prost-reflect = { version = "0.6.1", features = ["serde"] }
rand = "0.8.5"
regex = "1.5.4"
rustls = { version = "0.19.1", features = ["dangerous_configuration"] }
serde-transcode = "1.1.1"
serde_json = "1.0.79"
tokio-stream = "0.1.8"
tracing = "0.1.31"
tracing-subscriber = { version = "0.3.9", features = ["env-filter"] }
webpki = "0.21.4"
which = "4.2.4"

[dependencies.druid]
git = "https://github.com/linebender/druid.git"
branch = "master"
default-features = false
features = ["im", "svg", "serde", "x11"]

[dependencies.tonic]
version = "0.6.2"
default-features = false
features = ["transport", "tls", "tls-roots", "compression"]

[dependencies.tokio]
version = "1.16.1"
features = ["rt-multi-thread", "sync", "fs"]

[dependencies.serde]
version = "1.0.136"
features = ["derive", "rc"]

[dependencies.kurbo]
version = "0.8.3"
features = ["serde"]

[dependencies.im]
version = "15.0.0"
features = ["serde"]

[build-dependencies]
anyhow = "1.0.56"

[build-dependencies.vergen]
version = "6.0.2"
default-features = false
features = ["git"]

[patch.crates-io]
piet = { git = "https://github.com/linebender/piet", branch = "master" }
