on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Continuous integration

jobs:
  check:
    name: Lints and tests
    runs-on: ubuntu-latest
    steps:
      - name: Install libgtk-3-dev
        run: |
          sudo apt update
          sudo apt install libgtk-3-dev

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - uses: dtolnay/rust-toolchain@stable

      - run: cargo fmt --all -- --check

      - run: cargo clippy -- -D warnings

      - run: cargo check --all-features
