on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Continuous integration

jobs:
  check:
    name: Lints and tests
    runs-on: ubuntu-latest
    steps:
      - name: install libgtk-3-dev
        run: |
          sudo apt update
          sudo apt install libgtk-3-dev

      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
